hw2 done
vbegunova/nodejs-homework-rest-api pull request #1
Opened 2023-09-29 16:45 UTC by vbegunova

2023-09-29 17:47 UTC, ceREAL133 requested changes

2023-09-29 17:47 UTC, ceREAL133 commented on routes/api/contacts.js
> +});
схема повинна бути в окремому файлі

2023-09-29 18:38 UTC, vbegunova commented on routes/api/contacts.js
> +});
Винесла схеми в інший файл та винесла окремо допоміжну функцію, яка викидує помилки

2023-09-30 08:56 UTC, ceREAL133 approved these changes

2023-10-05 15:04 UTC, merged